[workspace]
members = [
    "crates/assembler",
    "crates/decompiler",
    "crates/vm",
    "crates/compiler"
]

default-members = ["crates/assembler", "crates/decompiler", "crates/vm", "crates/compiler"]