[workspace]
members = [
    "crates/assembler",
    "crates/compiler",
    "crates/decompiler",
    "crates/emulator",

]

default-members = ["crates/compiler", "crates/assembler", "crates/decompiler", "crates/emulator"]

